# Generated by Django 2.1.1 on 2018-09-07 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OurUsers',
            fields=[
                ('name', models.CharField(max_length=30)),
                ('dob', models.DateField()),
                ('username', models.EmailField(max_length=50, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=20)),
                ('profile_picture', models.ImageField(blank=True, upload_to='profile_pictures/')),
                ('friends', models.ManyToManyField(null=True, related_name='_ourusers_friends_+', to='friendzoned.OurUsers')),
            ],
        ),
    ]
